# Generated by Django 4.2.18 on 2025-04-04 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_field_2_remove_post_field_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='new_field',
        ),
    ]
